name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: cd ./AndroRPC-android-app && chmod +x ./gradlew
    - name: Build with Gradle
      run: cd ./AndroRPC-android-app && ./gradlew build
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: "Get pkg"
      run: npm install -g pkg
    - name: "Build with pkg"
      run: cd ./AndroRPC-server && pkg ./server.js
    - name: Upload Android Build
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "app-debug"
        path: ./AndroRPC-android-app/app/build/outputs/apk/debug/app-debug.apk
    - name: Upload Linux Build
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "linux"
        path: ./AndroRPC-server/server-linux
    - name: Upload Windows Build
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "windows"
        path: ./AndroRPC-server/server-win.exe
    - name: Upload OSX Build
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "macos"
        path: ./AndroRPC-server/server-macos
