name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: cd ./AndroRPC-android-app && chmod +x ./gradlew
    - name: Build with Gradle
      run: cd ./AndroRPC-android-app && ./gradlew build
    - name: Upload Build Result
      uses: actions/upload-artifact@v2.2.4
      with:
        name: "app-debug"
        path: ./AndroRPC-android-app/app/build/outputs/apk/debug/app-debug.apk
